### PR TITLE
RDD Graph (spree part)

### PR DESCRIPTION
**Pull request by sadikovi**
This PR adds functionality to display RDD DAG in Stage and Job views, very similar (essentially copy of Spark UI visualization) with some minor tweaks for React. Note that this does not support links on DAG right now, I tried fixing it, but could not because of weird `indexOf` error.

Should be merged together with similar PRs for json-relay and slim.

### CODE REVIEW

**Comment by sadikovi** [comment]
There is a bug with not displaying skipped stages correctly.

**Comment by ryan-williams** [comment]
thanks @sadikovi, sry for the continued delay, I am trying to page all this stuff in ASAP, but still waylaid; had to move apartments immediately when I returned from traveling on Sunday! Thanks for your patience, I look forward to reviewing all these!

**Comment by sadikovi** [comment]
~There is also bug with displaying stages in Job page, stages should be sorted by id, otherwise all DAGs become messed up.~ Fixed.
Spree DAG:
job 1 - spark - mozilla firefox_001

Spark DAG:
spark shell - details for job 1 - mozilla firefox_002

**Comment by sadikovi** [comment]
@ryan-williams thank you very much!
I hope that with my PRs did not break spree functionality:)

**Comment by sadikovi** [comment]
query used to test this job:

``` scala
val df1 = sqlContext.range(0, 100).filter($"id" > 3)
val df2 = sqlContext.range(0, 10000).filter($"id" > 12)
val df = df1.join(df2, "id").cache()
df.select($"id", lit(1), lit(true)).cache().count
```

**Comment by sadikovi** [comment]
Fixed sorting problem and marking skipped stages, note that these changes are valid only with corresponding changes in `spark-json-relay` and `slim`.

**Comment by sadikovi** [comment]
ping @ryan-williams

**Pull request closed without merging**
